export enum CustomErrorStatusCode {
  DUPLICATE_EMAIL = 600,
  DUPLICATE_USER_NAME = 601,
  DUPLICATE_TAG_TYPE = 602,
  DUPLICATE_TAG_NAME = 603,
  NO_UPDATES_MADE = 610,
  NO_DELETES_MADE = 611,
  NOT_FOUND_TAG = 620,
  NOT_FOUND_TAG_TYPE = 621,
  NOT_FOUND_MEMO = 622,
}
